// File: data/courseData.ts
export const courses = [
    {
        id: 1,
        title: 'Advanced Mathematics',
        description: 'Master calculus, linear algebra, and advanced mathematical concepts with practical applications.',
        teacher: 'Dr. Sarah Johnson',
        category: 'mathematics',
        level: 'Advanced',
        duration: '16 weeks',
        totalLessons: 24,
        completedLessons: 20,
        students: 45,
        rating: 4.8,
        progress: 85,
        thumbnail: 'https://images.pexels.com/photos/6238288/pexels-photo-6238288.jpeg?auto=compress&cs=tinysrgb&w=400&h=250&fit=crop',
        isEnrolled: true,
        nextLesson: 'Integration by Parts',
        lastAccessed: '2 hours ago',
        videoUrl: 'https://youtu.be/OfBqtyVvzaA',
        hoursStudied: 32,
        completed: false
    },
    {
        id: 2,
        title: 'Computer Science Fundamentals',
        description: 'Learn programming basics, data structures, algorithms, and software development principles.',
        teacher: 'Prof. Mike Chen',
        category: 'computer-science',
        level: 'Intermediate',
        duration: '20 weeks',
        totalLessons: 30,
        completedLessons: 19,
        students: 32,
        rating: 4.9,
        progress: 65,
        thumbnail: 'https://images.pexels.com/photos/577585/pexels-photo-577585.jpeg?auto=compress&cs=tinysrgb&w=400&h=250&fit=crop',
        isEnrolled: true,
        nextLesson: 'Binary Search Trees',
        lastAccessed: '1 day ago',
        videoUrl: 'https://youtu.be/OfBqtyVvzaA',
        hoursStudied: 28,
        completed: false
    },
    {
        id: 3,
        title: 'Physics Laboratory',
        description: 'Hands-on experiments covering mechanics, thermodynamics, and electromagnetic phenomena.',
        teacher: 'Dr. Emily Davis',
        category: 'physics',
        level: 'Intermediate',
        duration: '12 weeks',
        totalLessons: 20,
        completedLessons: 9,
        students: 28,
        rating: 4.7,
        progress: 45,
        thumbnail: 'https://images.pexels.com/photos/2280571/pexels-photo-2280571.jpeg?auto=compress&cs=tinysrgb&w=400&h=250&fit=crop',
        isEnrolled: true,
        nextLesson: 'Wave Interference',
        lastAccessed: '3 days ago',
        videoUrl: 'https://youtu.be/OfBqtyVvzaA',
        hoursStudied: 18,
        completed: false
    },
    {
        id: 4,
        title: 'Statistics & Probability',
        description: 'Statistical analysis, probability theory, and data interpretation for real-world applications.',
        teacher: 'Prof. Alex Wilson',
        category: 'mathematics',
        level: 'Intermediate',
        duration: '14 weeks',
        totalLessons: 22,
        completedLessons: 7,
        students: 35,
        rating: 4.6,
        progress: 30,
        thumbnail: 'https://images.pexels.com/photos/590022/pexels-photo-590022.jpeg?auto=compress&cs=tinysrgb&w=400&h=250&fit=crop',
        isEnrolled: true,
        nextLesson: 'Normal Distribution',
        lastAccessed: '5 days ago',
        videoUrl: 'https://youtu.be/OfBqtyVvzaA',
        hoursStudied: 12,
        completed: false
    },
    {
        id: 5,
        title: 'Organic Chemistry',
        description: 'Explore molecular structures, reactions, and mechanisms in organic chemistry.',
        teacher: 'Dr. Lisa Brown',
        category: 'chemistry',
        level: 'Advanced',
        duration: '18 weeks',
        totalLessons: 26,
        completedLessons: 0,
        students: 22,
        rating: 4.5,
        progress: 0,
        thumbnail: 'https://images.pexels.com/photos/2280549/pexels-photo-2280549.jpeg?auto=compress&cs=tinysrgb&w=400&h=250&fit=crop',
        isEnrolled: false,
        nextLesson: 'Introduction to Organic Compounds',
        lastAccessed: null,
        videoUrl: 'https://youtu.be/OfBqtyVvzaA',
        hoursStudied: 0,
        completed: false
    },
    {
        id: 6,
        title: 'Web Development Bootcamp',
        description: 'Full-stack web development with HTML, CSS, JavaScript, React, and Node.js.',
        teacher: 'Prof. David Kim',
        category: 'computer-science',
        level: 'Beginner',
        duration: '24 weeks',
        totalLessons: 40,
        completedLessons: 0,
        students: 18,
        rating: 4.9,
        progress: 0,
        thumbnail: 'https://images.pexels.com/photos/11035380/pexels-photo-11035380.jpeg?auto=compress&cs=tinysrgb&w=400&h=250&fit=crop',
        isEnrolled: false,
        nextLesson: 'HTML Basics',
        lastAccessed: null,
        videoUrl: 'https://youtu.be/OfBqtyVvzaA',
        hoursStudied: 0,
        completed: false
    }
];